import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConvexClientProvider from "./ConvexClerkProvider";
import { ClerkProvider } from "@clerk/nextjs";
import SyncClerkToConvex from "./syncUser";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NotableCV - AI-Powered Cover Letter Generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ClerkProvider>
          <ConvexClientProvider>
          {children}
            <SyncClerkToConvex />
          </ConvexClientProvider>
          </ClerkProvider>
        </body>
      </html>
  );
}
